# pyproject.toml
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "fixr"
description = "Python bindings to xrif, the extreme reordered image format"
version = "0.2.3"
requires-python = ">=3.9"
readme = "README.md"
dependencies = [
    "numpy>=2",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.cibuildwheel]
manylinux-x86_64-image = "quay.io/pypa/manylinux_2_28_x86_64"
manylinux-aarch64-image = "quay.io/pypa/manylinux_2_28_aarch64"

build = [
    "cp*-manylinux_aarch64",
    "cp*-manylinux_x86_64",
    "cp*-macosx_arm64",
    "cp*-macosx_universal2",
]
