# pyproject.toml
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "fixr"
version = "0.0.1"
requires-python = ">=3.8"

[tool.setuptools.packages.find]
where = ["src"]

[tool.cibuildwheel]

# Run a script that's inside your project
before-build = "bash build_xrif_and_generate_bindings.sh"
